[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ozon-barcode-reader"
version = "1.0.0"
description = "Инженерный проект чтения штрихкодов на конвейере"
requires-python = ">=3.12"
authors = [{name = "Karim Gimadiev"}]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
include = ["barcode_reader*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-ra"

